name: raytracer-push-checker

on:
  push:
    branches:
      - "dev"
      - "actions"
  pull_request:
    branches:
      - "main"

env:
  EXECUTABLES: "binary"
  ARGUMENTS: ""
  BIN_NAME: raytracer

jobs:
  check_compilation:
    name: "Check the compilation of the binary."
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thomas-pommier-epi/epitest-fast:cppgraphic

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing further dependencies
        run: |
          curl --output conf.rpm https://rpmfind.net/linux/fedora/linux/releases/38/Everything/x86_64/os/Packages/l/libconfig-1.7.3-5.fc38.x86_64.rpm
          rpm -ivh conf.rpm

      - name: Checking Makefile.
        run: |
          make
          if [ $? -ne 0 ]; then
            echo "Make failed."
            exit 1
          fi
          if [ ! -f "${{ env.BIN_NAME }}" ]; then
            echo "Bin not found."
            exit 1
          fi
        timeout-minutes: 4

      - name: Compiling and running tests.
        run: |
          make tests_run
          if [ $? -ne 0 ]; then
            echo "Make failed."
            exit 1
          fi

  merge_to_main:
    runs-on: ubuntu-latest
    needs: check_compilation
    if: ${{ github.ref == 'refs/heads/dev' && needs.check_compilation.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Merge to Main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git merge ${{ github.event.after }}
          git push origin main
